// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewLoco.Data;

#nullable disable

namespace NewLoco.Data.Migrations
{
    [DbContext(typeof(LocoDbContext))]
    [Migration("20260212230557_SeedSampleLocomotivesAndData")]
    partial class SeedSampleLocomotivesAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NewLoco.Data.Models.Fuel.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalFuel")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InitialFuel")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocoId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Refueled")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocoId");

                    b.ToTable("Fuels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 100m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3913),
                            Date = new DateOnly(2026, 1, 12),
                            FinalFuel = 400m,
                            InitialFuel = 500m,
                            IsDeleted = false,
                            LocoId = 1,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 2,
                            Consumption = 100m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3920),
                            Date = new DateOnly(2026, 1, 13),
                            FinalFuel = 300m,
                            InitialFuel = 400m,
                            IsDeleted = false,
                            LocoId = 1,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 3,
                            Consumption = 100m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3923),
                            Date = new DateOnly(2026, 1, 14),
                            FinalFuel = 200m,
                            InitialFuel = 300m,
                            IsDeleted = false,
                            LocoId = 1,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 4,
                            Consumption = 25m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3927),
                            Date = new DateOnly(2026, 1, 12),
                            FinalFuel = 975m,
                            InitialFuel = 1000m,
                            IsDeleted = false,
                            LocoId = 2,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 5,
                            Consumption = 25m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3930),
                            Date = new DateOnly(2026, 1, 13),
                            FinalFuel = 950m,
                            InitialFuel = 975m,
                            IsDeleted = false,
                            LocoId = 2,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 6,
                            Consumption = 25m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3933),
                            Date = new DateOnly(2026, 1, 14),
                            FinalFuel = 925m,
                            InitialFuel = 950m,
                            IsDeleted = false,
                            LocoId = 2,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 7,
                            Consumption = 30m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3937),
                            Date = new DateOnly(2026, 1, 12),
                            FinalFuel = 1470m,
                            InitialFuel = 1500m,
                            IsDeleted = false,
                            LocoId = 3,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 8,
                            Consumption = 30m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3940),
                            Date = new DateOnly(2026, 1, 13),
                            FinalFuel = 1440m,
                            InitialFuel = 1470m,
                            IsDeleted = false,
                            LocoId = 3,
                            Refueled = 0m
                        },
                        new
                        {
                            Id = 9,
                            Consumption = 30m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(3943),
                            Date = new DateOnly(2026, 1, 14),
                            FinalFuel = 1410m,
                            InitialFuel = 1440m,
                            IsDeleted = false,
                            LocoId = 3,
                            Refueled = 0m
                        });
                });

            modelBuilder.Entity("NewLoco.Data.Models.Locomotive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocomotiveType")
                        .HasColumnType("int");

                    b.Property<int>("MeasuringUnit")
                        .HasColumnType("int")
                        .HasComment(" Mh or Km");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Locomotives", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(9951),
                            IsDeleted = false,
                            LocomotiveType = 1,
                            MeasuringUnit = 1,
                            Number = "52-101"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(9955),
                            IsDeleted = false,
                            LocomotiveType = 1,
                            MeasuringUnit = 2,
                            Number = "55-203"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 506, DateTimeKind.Utc).AddTicks(9957),
                            IsDeleted = false,
                            LocomotiveType = 2,
                            MeasuringUnit = 2,
                            Number = "06-029"
                        });
                });

            modelBuilder.Entity("NewLoco.Data.Models.ShiftWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalValue")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InitialValue")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocoId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocoId");

                    b.ToTable("ShiftWorks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3723),
                            Date = new DateOnly(2026, 1, 12),
                            FinalValue = 105m,
                            InitialValue = 100m,
                            IsDeleted = false,
                            LocoId = 1,
                            Shift = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 5m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3729),
                            Date = new DateOnly(2026, 1, 13),
                            FinalValue = 110m,
                            InitialValue = 105m,
                            IsDeleted = false,
                            LocoId = 1,
                            Shift = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3732),
                            Date = new DateOnly(2026, 1, 14),
                            FinalValue = 115m,
                            InitialValue = 110m,
                            IsDeleted = false,
                            LocoId = 1,
                            Shift = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3735),
                            Date = new DateOnly(2026, 1, 12),
                            FinalValue = 5050m,
                            InitialValue = 5000m,
                            IsDeleted = false,
                            LocoId = 2,
                            Shift = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 50m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3738),
                            Date = new DateOnly(2026, 1, 13),
                            FinalValue = 5100m,
                            InitialValue = 5050m,
                            IsDeleted = false,
                            LocoId = 2,
                            Shift = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 50m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3742),
                            Date = new DateOnly(2026, 1, 14),
                            FinalValue = 5150m,
                            InitialValue = 5100m,
                            IsDeleted = false,
                            LocoId = 2,
                            Shift = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3745),
                            Date = new DateOnly(2026, 1, 12),
                            FinalValue = 10050m,
                            InitialValue = 10000m,
                            IsDeleted = false,
                            LocoId = 3,
                            Shift = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 50m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3748),
                            Date = new DateOnly(2026, 1, 13),
                            FinalValue = 10100m,
                            InitialValue = 10050m,
                            IsDeleted = false,
                            LocoId = 3,
                            Shift = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 2, 12, 23, 5, 56, 507, DateTimeKind.Utc).AddTicks(3751),
                            Date = new DateOnly(2026, 1, 14),
                            FinalValue = 10150m,
                            InitialValue = 10100m,
                            IsDeleted = false,
                            LocoId = 3,
                            Shift = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewLoco.Data.Models.Fuel.Fuel", b =>
                {
                    b.HasOne("NewLoco.Data.Models.Locomotive", "Locomotive")
                        .WithMany("Fuels")
                        .HasForeignKey("LocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("NewLoco.Data.Models.ShiftWork", b =>
                {
                    b.HasOne("NewLoco.Data.Models.Locomotive", "Locomotive")
                        .WithMany("ShiftWorks")
                        .HasForeignKey("LocoId")
                        .IsRequired();

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("NewLoco.Data.Models.Locomotive", b =>
                {
                    b.Navigation("Fuels");

                    b.Navigation("ShiftWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
