// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewLoco.Data;

#nullable disable

namespace NewLoco.Data.Migrations
{
    [DbContext(typeof(LocoDbContext))]
    [Migration("20260331161742_AddedSelectedLocomotiveIdToAxleMeasuremetCard")]
    partial class AddedSelectedLocomotiveIdToAxleMeasuremetCard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NewLoco.Data.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("NewLoco.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WorkNumber")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NewLoco.Data.Models.AxleMeasurementCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AxleCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SelectedLocomotiveId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelectedLocomotiveId");

                    b.HasIndex("Year", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("AxleMeasurementCards");
                });

            modelBuilder.Entity("NewLoco.Data.Models.AxleMeasurementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Ar")
                        .HasColumnType("float");

                    b.Property<int>("AxleMeasurementCardId")
                        .HasColumnType("int");

                    b.Property<int>("AxleNumber")
                        .HasColumnType("int");

                    b.Property<double?>("Sd_Left")
                        .HasColumnType("float");

                    b.Property<double?>("Sd_Right")
                        .HasColumnType("float");

                    b.Property<double?>("Sh_Left")
                        .HasColumnType("float");

                    b.Property<double?>("Sh_Right")
                        .HasColumnType("float");

                    b.Property<double?>("Sr")
                        .HasColumnType("float");

                    b.Property<double?>("qR_Left")
                        .HasColumnType("float");

                    b.Property<double?>("qR_Right")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AxleMeasurementCardId");

                    b.ToTable("AxleMeasurementValues");
                });

            modelBuilder.Entity("NewLoco.Data.Models.Fuel.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalFuel")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InitialFuel")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocoId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Refueled")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocoId", "Date", "Shift");

                    b.ToTable("Fuels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 100m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 400m,
                            InitialFuel = 500m,
                            IsDeleted = false,
                            LocoId = 1,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 2,
                            Consumption = 100m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 300m,
                            InitialFuel = 400m,
                            IsDeleted = false,
                            LocoId = 1,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 3,
                            Consumption = 100m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 200m,
                            InitialFuel = 300m,
                            IsDeleted = false,
                            LocoId = 1,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 4,
                            Consumption = 25m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 975m,
                            InitialFuel = 1000m,
                            IsDeleted = false,
                            LocoId = 2,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 5,
                            Consumption = 25m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 950m,
                            InitialFuel = 975m,
                            IsDeleted = false,
                            LocoId = 2,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 6,
                            Consumption = 25m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 925m,
                            InitialFuel = 950m,
                            IsDeleted = false,
                            LocoId = 2,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 7,
                            Consumption = 30m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 1470m,
                            InitialFuel = 1500m,
                            IsDeleted = false,
                            LocoId = 3,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 8,
                            Consumption = 30m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 1440m,
                            InitialFuel = 1470m,
                            IsDeleted = false,
                            LocoId = 3,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        },
                        new
                        {
                            Id = 9,
                            Consumption = 30m,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalFuel = 1410m,
                            InitialFuel = 1440m,
                            IsDeleted = false,
                            LocoId = 3,
                            Note = "",
                            Refueled = 0m,
                            Shift = 1
                        });
                });

            modelBuilder.Entity("NewLoco.Data.Models.Locomotive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AxlesCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocomotiveType")
                        .HasColumnType("int");

                    b.Property<int>("MeasuringUnit")
                        .HasColumnType("int")
                        .HasComment(" Mh or Km");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Locomotives", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AxlesCount = 0,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 31, 16, 17, 40, 735, DateTimeKind.Utc).AddTicks(7052),
                            IsDeleted = false,
                            LocomotiveType = 1,
                            MeasuringUnit = 1,
                            Note = "",
                            Number = "52-101"
                        },
                        new
                        {
                            Id = 2,
                            AxlesCount = 0,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 31, 16, 17, 40, 735, DateTimeKind.Utc).AddTicks(7058),
                            IsDeleted = false,
                            LocomotiveType = 1,
                            MeasuringUnit = 2,
                            Note = "",
                            Number = "55-203"
                        },
                        new
                        {
                            Id = 3,
                            AxlesCount = 0,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 31, 16, 17, 40, 735, DateTimeKind.Utc).AddTicks(7062),
                            IsDeleted = false,
                            LocomotiveType = 2,
                            MeasuringUnit = 2,
                            Note = "",
                            Number = "06-029"
                        });
                });

            modelBuilder.Entity("NewLoco.Data.Models.ShiftWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocomotiveId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocomotiveId");

                    b.ToTable("ShiftWorks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("NewLoco.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NewLoco.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NewLoco.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("NewLoco.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewLoco.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NewLoco.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewLoco.Data.Models.AxleMeasurementCard", b =>
                {
                    b.HasOne("NewLoco.Data.Models.Locomotive", "Locomotive")
                        .WithMany()
                        .HasForeignKey("SelectedLocomotiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("NewLoco.Data.Models.AxleMeasurementValue", b =>
                {
                    b.HasOne("NewLoco.Data.Models.AxleMeasurementCard", "AxleMeasurementCard")
                        .WithMany("Axles")
                        .HasForeignKey("AxleMeasurementCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AxleMeasurementCard");
                });

            modelBuilder.Entity("NewLoco.Data.Models.Fuel.Fuel", b =>
                {
                    b.HasOne("NewLoco.Data.Models.Locomotive", "Locomotive")
                        .WithMany("Fuels")
                        .HasForeignKey("LocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("NewLoco.Data.Models.ShiftWork", b =>
                {
                    b.HasOne("NewLoco.Data.Models.Locomotive", "Locomotive")
                        .WithMany("ShiftWorks")
                        .HasForeignKey("LocomotiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("NewLoco.Data.Models.AxleMeasurementCard", b =>
                {
                    b.Navigation("Axles");
                });

            modelBuilder.Entity("NewLoco.Data.Models.Locomotive", b =>
                {
                    b.Navigation("Fuels");

                    b.Navigation("ShiftWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
