<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>99aa5243-4e48-4e80-b9ed-3621a362aecb</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.23" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.23" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.23" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.23" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.23" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
	  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GCommon\GCommon.csproj" />
		<ProjectReference Include="..\NewLoco.Service.Core\NewLoco.Service.Core.csproj" />
		<ProjectReference Include="..\NewLoco.Data\NewLoco.Data.csproj" />
	</ItemGroup>
</Project>